#!/usr/bin/python

from upsiloncommon import *

parser = commonArgumentParser()
args = parser.parse_args();

client = getHttpClient(args.ssl, args.address, args.port);
resp = getHttpContent(client, "/peerUpdate")

print resp
