#!/usr/bin/python

import httplib
from lxml import etree
from prettytable import PrettyTable
import argparse

def bool2string(string, txt_true = "True", txt_false = "False"):
	if string.lower() in ["yes", "true", "1"]:
		return txt_true
	else:
		return txt_false

parser = argparse.ArgumentParser();
parser.add_argument('--address', '-a', help = "Hostname or IP address of upsilon-node", default = "localhost")
parser.add_argument('--port', '-p', help = "Port", default = 4000)
parser.add_argument('--ssl', action = "store_true")
args = parser.parse_args();

if args.ssl:
	httpClient = httplib.HTTPSConnection(args.address + ":" + str(args.port), timeout=2)
else:
	httpClient = httplib.HTTPConnection(args.address + ":" + str(args.port), timeout=2)

req = httpClient.request("GET", "/internalStatus");
res = httpClient.getresponse()

assert res.status == 200

resp = res.read()

assert len(resp) > 0

xml = etree.XML(resp)

configFiles = PrettyTable(["Filename", "Schema", "Parse status"])

for config in xml.xpath("//configStatuses"):
	configFiles.add_row([
		config.xpath("./path/text()")[0],
		bool2string(config.xpath("./isAux/text()")[0], "AUX", "MAIN"),
		bool2string(config.xpath("./isParseClean/text()")[0], "Clean", "ERROR")
	])

print configFiles
