#!/usr/bin/python

from upsiloncommon import *
import sys
from lxml import etree
from prettytable import PrettyTable
import argparse

def bool2string(string, txt_true = "True", txt_false = "False"):
	if string.lower() in ["yes", "true", "1"]:
		return txt_true
	else:
		return txt_false

parser = commonArgumentParser()
args = parser.parse_args();

client = getHttpClient(args.ssl, args.address, args.port, args.timeout);
resp = getHttpContent(client, "/internalStatus")

xml = etree.XML(resp)

internalStatus = PrettyTable(["Property", "Status"])
internalStatus.add_row(["Version", xml.xpath("//version/text()")[0]])
internalStatus.add_row(["Encryption (SSL/TLS)", bool2string(xml.xpath("//crypto/text()")[0], "Enabled", "Disabled")])
internalStatus.add_row(["Start time", xml.xpath("//startTime/text()")[0]])
internalStatus.add_row(["PID", xml.xpath("//pid/text()")[0]])
internalStatus.add_row(["Java VM", xml.xpath("//vm/text()")[0]])
internalStatus.add_row(["Java Classpath", xml.xpath("//classpath/text()")[0]])

print internalStatus
