#!/usr/bin/python

from upsiloncommon import *
from lxml import etree
from prettytable import PrettyTable
import argparse

def bool2string(string, txt_true = "True", txt_false = "False"):
	if string.lower() in ["yes", "true", "1"]:
		return txt_true
	else:
		return txt_false

parser = argparse.ArgumentParser();
parser.add_argument('--address', '-a', help = "Hostname or IP address of upsilon-node", default = "localhost")
parser.add_argument('--port', '-p', help = "Port", default = 4000)
parser.add_argument('--ssl', action = "store_true")
args = parser.parse_args();

client = getHttpClient(args.ssl, args.address, args.port)
res = getHttpContent(client, "/internalStatus")

xml = etree.XML(res)

configFiles = PrettyTable(["Filename", "Schema", "Parse status"])

for config in xml.xpath("//configStatuses"):
	configFiles.add_row([
		config.xpath("./path/text()")[0],
		bool2string(config.xpath("./isAux/text()")[0], "AUX", "MAIN"),
		bool2string(config.xpath("./isParseClean/text()")[0], "Clean", "ERROR")
	])

print configFiles
