#!/usr/bin/python

from upsiloncommon import error
import argparse
from lxml import etree
import re
import os
import commands

parser = argparse.ArgumentParser();
group = parser.add_mutually_exclusive_group(required = True)
group.add_argument('-l', '--list', action = 'store_true')
group.add_argument('-c', '--command')
args = parser.parse_args()

config = open('/etc/upsilon-node/config.xml', 'r');
configStr = config.read();

tree = etree.XML(configStr)

if args.list:
	for command in tree.xpath("//command"):
		print command.attrib.get("id")
elif args.command != None: 
	query = "//command[@id='" + args.command + "']"
	search = tree.xpath(query)

	if len(search) == 0:
		error("Command not found. List available commands with -l")
	else:
		command = search[0]
		print "Command:", command.attrib.get("id")

		commandExec = command.attrib.get("exec")
		m = re.search(".+(\$[\w]+).+", commandExec)
		
		argKeys = m.groups()
		argValues = dict()

		for arg in argKeys:
			answer = raw_input("Value for: " + arg + "?: ")
			commandExec = commandExec.replace(arg, answer)
			argValues[arg] = answer

		print 
		print "Executing:", commandExec
		print 

		status, output = commands.getstatusoutput(commandExec)

		for line in output.split("\n"):
			print ">> ", line

		print 
		print "Exit status:", status
