#!/usr/bin/python

import errno
import yum 
import argparse
from upsiloncommon import error, getHttpClient, getHttpContent
import re

parser = argparse.ArgumentParser()
parser.add_argument("-c", "--command", required = True)
args = parser.parse_args()

def installPackagesYum(lookedUpCommand):
	print "yum install:", lookedUpCommand
	packageName = lookedUpCommand['content']

	yb=yum.YumBase()
	packageSearchResults = yb.rpmdb.searchNevra(name=packageName)
	#installed = yb.rpmdb.returnPackages()

	try:
		if len(packageSearchResults) == 0:
			print('Installing: {0}'.format(packageName))
			yb.install(name=packageName)
			yb.resolveDeps()
			yb.buildTransaction()

			yb.processTransaction()
		else:
			print('{0} is already installed, skipping...'.format(packageName))
	except IOError as e:
		if e[0] == errno.EACCES:
			error("Permission denied. Yum requires that you have root privileges to install a package.")
		else:
			error(e)

def getOsPackageSystem():
	if which("rpm"):
		return installPackagesYum

	return None

def which(program):
	import os
	def is_exe(fpath):
		return os.path.isfile(fpath) and os.access(fpath, os.X_OK)

	fpath, fname = os.path.split(program)
	if fpath:
		if is_exe(program):
			return program
	else:
		for path in os.environ["PATH"].split(os.pathsep):
		    path = path.strip('"')
		    exe_file = os.path.join(path, program)
		    if is_exe(exe_file):
			return exe_file

	return None

def lookupCommand(command):
	client = getHttpClient(False, "upsilon-project.co.uk")
	content = getHttpContent(client, "/site/index.php/" + command)

	# <span class="get-command rpm-fedora">nagios-plugins-pin
	search = '<span class="get-command ([\w\-\ ]+)">([\w_-]+)</span>'
	m = re.search(search, content)

	if m != None and len(m.groups()) == 2:
		return {
			"classes": m.group(1).split(' '),
			"content": m.group(2)
		}

	return None

def promptInstall(lookedUpCommand): 
	print "Classes:", ", ".join(lookedUpCommand['classes'])
	print "Content:", lookedUpCommand['content']
	return True

### 

lookedUpCommand = lookupCommand(args.command)

if lookedUpCommand == None or lookedUpCommand['content'] == "(none)":
	error("Command not found.");
else:
	if promptInstall(lookedUpCommand):
		osInstaller = getOsPackageSystem()

		if osInstaller == None:
			error("This tool does not support installation of packages on your OS.");
		else:
			osInstaller(lookedUpCommand)
